require 'require_all'

require 'aws-sdk'
require 'json'
require 'pry'
require 'dotenv/load'
require 'httparty'
require 'sidekiq'
require_all 'configs'
require_all 'lib/app'
# require_all 'lib/workers'
# require_all 'lib/services'
# require_all 'lib/apis'
